import importlib as _importlib
import sys as _sys

from .core import (
    AccountSnapshot,
    BacktestConfig,
    BacktestEngine,
    BacktestEvent,
    BacktestEventType,
    BacktestValidationIssue,
    BacktestValidationReport,
    BasicMetricsCalculator,
    BorrowCostModel,
    CashMarginLedger,
    CommissionModel,
    CompositeRiskModel,
    EventSink,
    ExecutionModel,
    Fill,
    InMemoryEventSink,
    LiquidityModel,
    MarginModel,
    MarketSnapshot,
    MetricsCalculator,
    OrderFactory,
    OrderRejection,
    PandasStrategySignalProvider,
    PortfolioLedger,
    RejectionReason,
    RiskModel,
    RiskPercentOrderFactory,
    SignalContext,
    SignalProvider,
    SimpleMarginModel,
    SimulationBatch,
    SlippageModel,
    run_backtest,
    validate_backtest_result,
)
from .execution import (
    AnnualizedBorrowCostModel,
    BacktestExecutionProfile,
    BarExecutionModel,
    BpsCommissionModel,
    CapacityAnalysisConfig,
    CapacityAnalysisReport,
    CapacityPoint,
    ExecutionParityResult,
    ExecutionParityScenario,
    FillObservation,
    FixedBpsSlippageModel,
    NoBorrowCostModel,
    NoSlippageModel,
    SpreadVolumeSlippageModel,
    StrategyCapacityProfile,
    TransactionCostCalibration,
    UnlimitedLiquidityModel,
    VolumeShareLiquidityModel,
    ZeroCommissionModel,
    analyze_backtest_capacity,
    analyze_capacity,
    capacity_profile_from_backtest,
    commission_model_for_broker,
    compare_capacity_reports,
)
from .research import (
    DEFAULT_STRATEGY_MODES,
    DEFAULT_FACTOR_SPREADS,
    DEFAULT_MARKET_CLUSTERS,
    REQUIRED_OPTIONS_CAPABILITIES,
    BenchmarkRelativeReport,
    CointegrationTestResult,
    ConfidenceInterval,
    CryptoAdaptiveAssetScore,
    CryptoAdaptiveSelectionConfig,
    CryptoAdaptiveSelectionReport,
    DynamicAllocationConfig,
    DynamicAllocationReport,
    DynamicAllocationTarget,
    DynamicMarketStressScore,
    EnsembleAllocationDecision,
    EnsembleAllocationPlan,
    EnsembleAllocationPolicy,
    FactorSpreadDefinition,
    FactorTrendConfig,
    FactorTrendLeg,
    FactorTrendReport,
    FactorTrendSignal,
    FactorExposureResult,
    MarketClusterDefinition,
    MarketClusterValidationPolicy,
    MarketClusterValidationReport,
    MarketRegimeConfig,
    MarketRegimeProfile,
    MultipleTestingResult,
    OptionChainSnapshot,
    OptionContract,
    OptionGreeks,
    OptionPosition,
    OptionQuote,
    OptionTailStressResult,
    OptionTailStressScenario,
    OptionsCapabilityStatus,
    OptionsPromotionGateResult,
    PairCandidate,
    PairTradeLeg,
    PairsResearchConfig,
    PairsResearchReport,
    ResearchFilterConfig,
    ResearchFilterResult,
    ResearchFilterSnapshot,
    ScorecardReport,
    StrategyActivationDecision,
    StrategyActivationReport,
    StrategyClusterResult,
    StrategyClusterSummary,
    StrategyBenchmarkComparison,
    StrategyBenchmarkSummary,
    StrategyFamilyCandidate,
    StrategyFamilyEnsemblePolicy,
    StrategyFamilyEnsembleReport,
    StrategyScorecardEntry,
    StrategySelectionPolicy,
    StrategySelectionReport,
    StylePremiaConfig,
    StylePremiaRankingReport,
    StylePremiaScore,
    SymbolResearchScorecard,
    SymbolStrategySelection,
    activate_strategies_for_regime,
    adjust_p_values,
    benchmark_relative_report,
    build_dynamic_allocation,
    build_ensemble_allocation,
    build_factor_trend_report,
    build_strategy_family_ensemble,
    build_style_premia_ranking,
    build_symbol_scorecards,
    choppiness_range_filter,
    classify_market_regime,
    classify_regime_universe,
    cointegration_test,
    confidence_interval,
    discover_stat_arb_pairs,
    evaluate_options_promotion_gate,
    evaluate_research_filters,
    fair_value_gap_filter,
    factor_exposure,
    intrinsic_value,
    liquidity_sweep_filter,
    select_crypto_adaptive_universe,
    select_strategies_against_benchmark,
    scipy_available,
    stress_option_position,
    structure_confirmation_filter,
    statsmodels_available,
    validate_market_clusters,
    vwap_stretch_filter,
)
from .runners import (
    BatchBacktestJob,
    BatchBacktestRunner,
    BatchBacktestSummary,
    BulkBacktestError,
    BulkBacktestRecord,
    BulkBacktestReport,
    GovernedWalkForwardWindow,
    MultiSymbolBacktestResult,
    OptimizationResult,
    OptunaOptimizationConfig,
    OptunaOptimizationReport,
    OptunaTrialRecord,
    OverfittingReport,
    PaperSessionManifest,
    PaperTradingExpectation,
    PaperTradingObservation,
    PaperTradingScorecard,
    PaperTradingScorecardGate,
    PaperTradingScorecardPolicy,
    ParameterStabilityReport,
    PromotionGateResult,
    PromotionPipelinePolicy,
    PromotionPipelineReport,
    ReplicationProfile,
    ReplicationReference,
    ReplicationReport,
    ReplicationRunResult,
    ReplicationSuite,
    ResearchAssetGroup,
    ResearchMatrixConfig,
    ResearchMatrixJob,
    ResearchMatrixJobResult,
    ResearchMatrixReport,
    ResearchWindow,
    ResearchCandidateEvidence,
    TradeCommitteeContext,
    TradeCommitteeDecision,
    TradeCommitteeGate,
    TradeCommitteePolicy,
    WalkForwardGovernanceConfig,
    WalkForwardGovernanceReport,
    WalkForwardWindow,
    build_paper_trading_scorecard,
    decide_trade_action,
    expand_research_matrix,
    evaluate_promotion_candidate,
    grid_search,
    load_replication_suite,
    load_research_matrix,
    optuna_available,
    overfitting_report,
    paper_scorecard_from_backtest,
    rank_optimization_results,
    replication_suite_from_dict,
    research_matrix_from_dict,
    run_bulk_backtests,
    run_multi_symbol_backtest,
    run_optuna_optimization,
    run_replication_suite,
    run_research_matrix,
    run_walk_forward,
    run_walk_forward_governance,
    write_replication_report,
)

__all__ = [
    "AccountSnapshot",
    "AnnualizedBorrowCostModel",
    "BacktestConfig",
    "BacktestEngine",
    "BacktestExecutionProfile",
    "BatchBacktestJob",
    "BatchBacktestRunner",
    "BatchBacktestSummary",
    "BacktestEvent",
    "BacktestEventType",
    "BacktestValidationIssue",
    "BacktestValidationReport",
    "BarExecutionModel",
    "BasicMetricsCalculator",
    "BenchmarkRelativeReport",
    "BorrowCostModel",
    "BpsCommissionModel",
    "BulkBacktestError",
    "BulkBacktestRecord",
    "BulkBacktestReport",
    "CashMarginLedger",
    "CapacityAnalysisConfig",
    "CapacityAnalysisReport",
    "CapacityPoint",
    "CointegrationTestResult",
    "CommissionModel",
    "CompositeRiskModel",
    "ConfidenceInterval",
    "CryptoAdaptiveAssetScore",
    "CryptoAdaptiveSelectionConfig",
    "CryptoAdaptiveSelectionReport",
    "DEFAULT_STRATEGY_MODES",
    "DynamicAllocationConfig",
    "DynamicAllocationReport",
    "DynamicAllocationTarget",
    "DynamicMarketStressScore",
    "EnsembleAllocationDecision",
    "EnsembleAllocationPlan",
    "EnsembleAllocationPolicy",
    "EventSink",
    "ExecutionModel",
    "ExecutionParityResult",
    "ExecutionParityScenario",
    "DEFAULT_FACTOR_SPREADS",
    "DEFAULT_MARKET_CLUSTERS",
    "FactorSpreadDefinition",
    "FactorTrendConfig",
    "FactorTrendLeg",
    "FactorTrendReport",
    "FactorTrendSignal",
    "FactorExposureResult",
    "Fill",
    "FillObservation",
    "FixedBpsSlippageModel",
    "GovernedWalkForwardWindow",
    "InMemoryEventSink",
    "LiquidityModel",
    "MarginModel",
    "MarketSnapshot",
    "MarketRegimeConfig",
    "MarketRegimeProfile",
    "MarketClusterDefinition",
    "MarketClusterValidationPolicy",
    "MarketClusterValidationReport",
    "MultipleTestingResult",
    "MetricsCalculator",
    "NoBorrowCostModel",
    "NoSlippageModel",
    "OrderFactory",
    "OrderRejection",
    "OptimizationResult",
    "OptunaOptimizationConfig",
    "OptunaOptimizationReport",
    "OptunaTrialRecord",
    "OptionChainSnapshot",
    "OptionContract",
    "OptionGreeks",
    "OptionPosition",
    "OptionQuote",
    "OptionTailStressResult",
    "OptionTailStressScenario",
    "OptionsCapabilityStatus",
    "OptionsPromotionGateResult",
    "OverfittingReport",
    "PaperSessionManifest",
    "PaperTradingExpectation",
    "PaperTradingObservation",
    "PaperTradingScorecard",
    "PaperTradingScorecardGate",
    "PaperTradingScorecardPolicy",
    "PairCandidate",
    "PairTradeLeg",
    "PairsResearchConfig",
    "PairsResearchReport",
    "MultiSymbolBacktestResult",
    "PandasStrategySignalProvider",
    "ParameterStabilityReport",
    "PortfolioLedger",
    "PromotionGateResult",
    "PromotionPipelinePolicy",
    "PromotionPipelineReport",
    "RejectionReason",
    "ReplicationProfile",
    "ReplicationReference",
    "ReplicationReport",
    "ReplicationRunResult",
    "ReplicationSuite",
    "ResearchFilterConfig",
    "ResearchFilterResult",
    "ResearchFilterSnapshot",
    "ResearchAssetGroup",
    "ResearchMatrixConfig",
    "ResearchMatrixJob",
    "ResearchMatrixJobResult",
    "ResearchMatrixReport",
    "ResearchWindow",
    "ResearchCandidateEvidence",
    "REQUIRED_OPTIONS_CAPABILITIES",
    "RiskModel",
    "RiskPercentOrderFactory",
    "ScorecardReport",
    "SignalContext",
    "SignalProvider",
    "SimpleMarginModel",
    "SimulationBatch",
    "SlippageModel",
    "SpreadVolumeSlippageModel",
    "StrategyActivationDecision",
    "StrategyActivationReport",
    "StrategyBenchmarkComparison",
    "StrategyBenchmarkSummary",
    "StrategyCapacityProfile",
    "StrategyFamilyCandidate",
    "StrategyFamilyEnsemblePolicy",
    "StrategyFamilyEnsembleReport",
    "StrategyClusterResult",
    "StrategyClusterSummary",
    "StrategyScorecardEntry",
    "StrategySelectionPolicy",
    "StrategySelectionReport",
    "StylePremiaConfig",
    "StylePremiaRankingReport",
    "StylePremiaScore",
    "SymbolStrategySelection",
    "SymbolResearchScorecard",
    "TransactionCostCalibration",
    "TradeCommitteeContext",
    "TradeCommitteeDecision",
    "TradeCommitteeGate",
    "TradeCommitteePolicy",
    "UnlimitedLiquidityModel",
    "VolumeShareLiquidityModel",
    "WalkForwardWindow",
    "WalkForwardGovernanceConfig",
    "WalkForwardGovernanceReport",
    "ZeroCommissionModel",
    "activate_strategies_for_regime",
    "adjust_p_values",
    "analyze_backtest_capacity",
    "analyze_capacity",
    "commission_model_for_broker",
    "benchmark_relative_report",
    "build_symbol_scorecards",
    "build_style_premia_ranking",
    "build_dynamic_allocation",
    "build_ensemble_allocation",
    "build_factor_trend_report",
    "build_paper_trading_scorecard",
    "build_strategy_family_ensemble",
    "capacity_profile_from_backtest",
    "choppiness_range_filter",
    "classify_market_regime",
    "classify_regime_universe",
    "cointegration_test",
    "compare_capacity_reports",
    "confidence_interval",
    "decide_trade_action",
    "discover_stat_arb_pairs",
    "evaluate_research_filters",
    "evaluate_options_promotion_gate",
    "expand_research_matrix",
    "evaluate_promotion_candidate",
    "fair_value_gap_filter",
    "factor_exposure",
    "grid_search",
    "optuna_available",
    "overfitting_report",
    "paper_scorecard_from_backtest",
    "rank_optimization_results",
    "intrinsic_value",
    "liquidity_sweep_filter",
    "load_research_matrix",
    "load_replication_suite",
    "run_multi_symbol_backtest",
    "run_optuna_optimization",
    "run_walk_forward",
    "run_walk_forward_governance",
    "run_backtest",
    "run_bulk_backtests",
    "run_research_matrix",
    "research_matrix_from_dict",
    "replication_suite_from_dict",
    "run_replication_suite",
    "scipy_available",
    "select_strategies_against_benchmark",
    "select_crypto_adaptive_universe",
    "structure_confirmation_filter",
    "stress_option_position",
    "validate_market_clusters",
    "validate_backtest_result",
    "vwap_stretch_filter",
    "statsmodels_available",
    "write_replication_report",
]

_MODULE_ALIASES = {
    "activation": "research.activation",
    "adapters": "core.adapters",
    "allocation": "research.allocation",
    "batch": "runners.batch",
    "bulk": "runners.bulk",
    "calibration": "execution.calibration",
    "capacity": "execution.capacity",
    "costs": "execution.costs",
    "crypto_adaptive": "research.crypto_adaptive",
    "dynamic_allocation": "research.dynamic_allocation",
    "engine": "core.engine",
    "factor_trend": "research.factor_trend",
    "filters": "research.filters",
    "governance": "runners.governance",
    "interfaces": "core.interfaces",
    "ledger": "core.ledger",
    "margin": "core.margin",
    "market_clusters": "research.market_clusters",
    "metrics": "core.metrics",
    "multi_symbol": "runners.multi_symbol",
    "optimization": "runners.optimization",
    "paper_scorecard": "runners.paper_scorecard",
    "promotion": "runners.promotion",
    "options_gate": "research.options_gate",
    "parity": "execution.parity",
    "profiles": "execution.profiles",
    "regime": "research.regime",
    "replication": "runners.replication",
    "research_matrix": "runners.research_matrix",
    "risk": "core.risk",
    "scorecards": "research.scorecards",
    "selection": "research.selection",
    "stat_arb": "research.stat_arb",
    "strategy_ensemble": "research.strategy_ensemble",
    "style_premia": "research.style_premia",
    "trade_committee": "runners.trade_committee",
    "types": "core.types",
    "validation": "core.validation",
    "walk_forward": "runners.walk_forward",
}

for _old_module, _new_module in _MODULE_ALIASES.items():
    _module = _importlib.import_module(f"{__name__}.{_new_module}")
    _sys.modules[f"{__name__}.{_old_module}"] = _module
    globals()[_old_module] = _module

del _importlib, _sys, _MODULE_ALIASES, _old_module, _new_module, _module
