from .adapters import PandasStrategySignalProvider, RiskPercentOrderFactory
from .activation import (
    DEFAULT_STRATEGY_MODES,
    StrategyActivationDecision,
    StrategyActivationReport,
    activate_strategies_for_regime,
)
from .allocation import (
    EnsembleAllocationDecision,
    EnsembleAllocationPlan,
    EnsembleAllocationPolicy,
    build_ensemble_allocation,
)
from .batch import BatchBacktestJob, BatchBacktestRunner, BatchBacktestSummary
from .bulk import BulkBacktestError, BulkBacktestRecord, BulkBacktestReport, run_bulk_backtests
from .calibration import FillObservation, TransactionCostCalibration
from .capacity import (
    CapacityAnalysisConfig,
    CapacityAnalysisReport,
    CapacityPoint,
    StrategyCapacityProfile,
    analyze_backtest_capacity,
    analyze_capacity,
    capacity_profile_from_backtest,
    compare_capacity_reports,
)
from .costs import (
    AnnualizedBorrowCostModel,
    BpsCommissionModel,
    FixedBpsSlippageModel,
    NoBorrowCostModel,
    NoSlippageModel,
    SpreadVolumeSlippageModel,
    UnlimitedLiquidityModel,
    VolumeShareLiquidityModel,
    ZeroCommissionModel,
    commission_model_for_broker,
)
from .crypto_adaptive import (
    CryptoAdaptiveAssetScore,
    CryptoAdaptiveSelectionConfig,
    CryptoAdaptiveSelectionReport,
    select_crypto_adaptive_universe,
)
from .dynamic_allocation import (
    DynamicAllocationConfig,
    DynamicAllocationReport,
    DynamicAllocationTarget,
    DynamicMarketStressScore,
    build_dynamic_allocation,
)
from .engine import BacktestEngine, InMemoryEventSink, run_backtest
from .execution import BarExecutionModel
from .factor_trend import (
    DEFAULT_FACTOR_SPREADS,
    FactorSpreadDefinition,
    FactorTrendConfig,
    FactorTrendLeg,
    FactorTrendReport,
    FactorTrendSignal,
    build_factor_trend_report,
)
from .filters import (
    ResearchFilterConfig,
    ResearchFilterResult,
    ResearchFilterSnapshot,
    choppiness_range_filter,
    evaluate_research_filters,
    fair_value_gap_filter,
    liquidity_sweep_filter,
    structure_confirmation_filter,
    vwap_stretch_filter,
)
from .governance import (
    GovernedWalkForwardWindow,
    ParameterStabilityReport,
    WalkForwardGovernanceConfig,
    WalkForwardGovernanceReport,
    run_walk_forward_governance,
)
from .interfaces import (
    BorrowCostModel,
    CommissionModel,
    EventSink,
    ExecutionModel,
    LiquidityModel,
    MarginModel,
    MetricsCalculator,
    OrderFactory,
    PortfolioLedger,
    RiskModel,
    SignalProvider,
    SlippageModel,
)
from .ledger import CashMarginLedger
from .market_clusters import (
    DEFAULT_MARKET_CLUSTERS,
    MarketClusterDefinition,
    MarketClusterValidationPolicy,
    MarketClusterValidationReport,
    StrategyClusterResult,
    StrategyClusterSummary,
    validate_market_clusters,
)
from .margin import SimpleMarginModel
from .metrics import BasicMetricsCalculator
from .multi_symbol import MultiSymbolBacktestResult, run_multi_symbol_backtest
from .optimization import OptimizationResult, OverfittingReport, grid_search, overfitting_report, rank_optimization_results
from .options_gate import (
    REQUIRED_OPTIONS_CAPABILITIES,
    OptionChainSnapshot,
    OptionContract,
    OptionGreeks,
    OptionPosition,
    OptionQuote,
    OptionTailStressResult,
    OptionTailStressScenario,
    OptionsCapabilityStatus,
    OptionsPromotionGateResult,
    evaluate_options_promotion_gate,
    intrinsic_value,
    stress_option_position,
)
from .parity import ExecutionParityResult, ExecutionParityScenario
from .profiles import BacktestExecutionProfile
from .regime import MarketRegimeConfig, MarketRegimeProfile, classify_market_regime, classify_regime_universe
from .research_matrix import (
    ResearchAssetGroup,
    ResearchMatrixConfig,
    ResearchMatrixJob,
    ResearchMatrixJobResult,
    ResearchMatrixReport,
    ResearchWindow,
    expand_research_matrix,
    load_research_matrix,
    research_matrix_from_dict,
    run_research_matrix,
)
from .replication import (
    ReplicationProfile,
    ReplicationReference,
    ReplicationReport,
    ReplicationRunResult,
    ReplicationSuite,
    load_replication_suite,
    replication_suite_from_dict,
    run_replication_suite,
    write_replication_report,
)
from .risk import CompositeRiskModel
from .scorecards import ScorecardReport, StrategyScorecardEntry, SymbolResearchScorecard, build_symbol_scorecards
from .selection import (
    BenchmarkRelativeReport,
    StrategyBenchmarkComparison,
    StrategyBenchmarkSummary,
    StrategySelectionPolicy,
    StrategySelectionReport,
    SymbolStrategySelection,
    benchmark_relative_report,
    select_strategies_against_benchmark,
)
from .stat_arb import (
    PairCandidate,
    PairTradeLeg,
    PairsResearchConfig,
    PairsResearchReport,
    discover_stat_arb_pairs,
)
from .style_premia import (
    StylePremiaConfig,
    StylePremiaRankingReport,
    StylePremiaScore,
    build_style_premia_ranking,
)
from .strategy_ensemble import (
    StrategyFamilyCandidate,
    StrategyFamilyEnsemblePolicy,
    StrategyFamilyEnsembleReport,
    build_strategy_family_ensemble,
)
from .types import (
    AccountSnapshot,
    BacktestConfig,
    BacktestEvent,
    BacktestEventType,
    Fill,
    MarketSnapshot,
    OrderRejection,
    RejectionReason,
    SignalContext,
    SimulationBatch,
)
from .validation import BacktestValidationIssue, BacktestValidationReport, validate_backtest_result
from .walk_forward import WalkForwardWindow, run_walk_forward

__all__ = [
    "AccountSnapshot",
    "AnnualizedBorrowCostModel",
    "BacktestConfig",
    "BacktestEngine",
    "BacktestExecutionProfile",
    "BatchBacktestJob",
    "BatchBacktestRunner",
    "BatchBacktestSummary",
    "BacktestEvent",
    "BacktestEventType",
    "BacktestValidationIssue",
    "BacktestValidationReport",
    "BarExecutionModel",
    "BasicMetricsCalculator",
    "BenchmarkRelativeReport",
    "BorrowCostModel",
    "BpsCommissionModel",
    "BulkBacktestError",
    "BulkBacktestRecord",
    "BulkBacktestReport",
    "CashMarginLedger",
    "CapacityAnalysisConfig",
    "CapacityAnalysisReport",
    "CapacityPoint",
    "CommissionModel",
    "CompositeRiskModel",
    "CryptoAdaptiveAssetScore",
    "CryptoAdaptiveSelectionConfig",
    "CryptoAdaptiveSelectionReport",
    "DEFAULT_STRATEGY_MODES",
    "DynamicAllocationConfig",
    "DynamicAllocationReport",
    "DynamicAllocationTarget",
    "DynamicMarketStressScore",
    "EnsembleAllocationDecision",
    "EnsembleAllocationPlan",
    "EnsembleAllocationPolicy",
    "EventSink",
    "ExecutionModel",
    "ExecutionParityResult",
    "ExecutionParityScenario",
    "DEFAULT_FACTOR_SPREADS",
    "DEFAULT_MARKET_CLUSTERS",
    "FactorSpreadDefinition",
    "FactorTrendConfig",
    "FactorTrendLeg",
    "FactorTrendReport",
    "FactorTrendSignal",
    "Fill",
    "FillObservation",
    "FixedBpsSlippageModel",
    "GovernedWalkForwardWindow",
    "InMemoryEventSink",
    "LiquidityModel",
    "MarginModel",
    "MarketSnapshot",
    "MarketRegimeConfig",
    "MarketRegimeProfile",
    "MarketClusterDefinition",
    "MarketClusterValidationPolicy",
    "MarketClusterValidationReport",
    "MetricsCalculator",
    "NoBorrowCostModel",
    "NoSlippageModel",
    "OrderFactory",
    "OrderRejection",
    "OptimizationResult",
    "OptionChainSnapshot",
    "OptionContract",
    "OptionGreeks",
    "OptionPosition",
    "OptionQuote",
    "OptionTailStressResult",
    "OptionTailStressScenario",
    "OptionsCapabilityStatus",
    "OptionsPromotionGateResult",
    "OverfittingReport",
    "PairCandidate",
    "PairTradeLeg",
    "PairsResearchConfig",
    "PairsResearchReport",
    "MultiSymbolBacktestResult",
    "PandasStrategySignalProvider",
    "ParameterStabilityReport",
    "PortfolioLedger",
    "RejectionReason",
    "ReplicationProfile",
    "ReplicationReference",
    "ReplicationReport",
    "ReplicationRunResult",
    "ReplicationSuite",
    "ResearchFilterConfig",
    "ResearchFilterResult",
    "ResearchFilterSnapshot",
    "ResearchAssetGroup",
    "ResearchMatrixConfig",
    "ResearchMatrixJob",
    "ResearchMatrixJobResult",
    "ResearchMatrixReport",
    "ResearchWindow",
    "REQUIRED_OPTIONS_CAPABILITIES",
    "RiskModel",
    "RiskPercentOrderFactory",
    "ScorecardReport",
    "SignalContext",
    "SignalProvider",
    "SimpleMarginModel",
    "SimulationBatch",
    "SlippageModel",
    "SpreadVolumeSlippageModel",
    "StrategyActivationDecision",
    "StrategyActivationReport",
    "StrategyBenchmarkComparison",
    "StrategyBenchmarkSummary",
    "StrategyCapacityProfile",
    "StrategyFamilyCandidate",
    "StrategyFamilyEnsemblePolicy",
    "StrategyFamilyEnsembleReport",
    "StrategyClusterResult",
    "StrategyClusterSummary",
    "StrategyScorecardEntry",
    "StrategySelectionPolicy",
    "StrategySelectionReport",
    "StylePremiaConfig",
    "StylePremiaRankingReport",
    "StylePremiaScore",
    "SymbolStrategySelection",
    "SymbolResearchScorecard",
    "TransactionCostCalibration",
    "UnlimitedLiquidityModel",
    "VolumeShareLiquidityModel",
    "WalkForwardWindow",
    "WalkForwardGovernanceConfig",
    "WalkForwardGovernanceReport",
    "ZeroCommissionModel",
    "activate_strategies_for_regime",
    "analyze_backtest_capacity",
    "analyze_capacity",
    "commission_model_for_broker",
    "benchmark_relative_report",
    "build_symbol_scorecards",
    "build_style_premia_ranking",
    "build_dynamic_allocation",
    "build_ensemble_allocation",
    "build_factor_trend_report",
    "build_strategy_family_ensemble",
    "capacity_profile_from_backtest",
    "choppiness_range_filter",
    "classify_market_regime",
    "classify_regime_universe",
    "compare_capacity_reports",
    "discover_stat_arb_pairs",
    "evaluate_research_filters",
    "evaluate_options_promotion_gate",
    "expand_research_matrix",
    "fair_value_gap_filter",
    "grid_search",
    "overfitting_report",
    "rank_optimization_results",
    "intrinsic_value",
    "liquidity_sweep_filter",
    "load_research_matrix",
    "load_replication_suite",
    "run_multi_symbol_backtest",
    "run_walk_forward",
    "run_walk_forward_governance",
    "run_backtest",
    "run_bulk_backtests",
    "run_research_matrix",
    "research_matrix_from_dict",
    "replication_suite_from_dict",
    "run_replication_suite",
    "select_strategies_against_benchmark",
    "select_crypto_adaptive_universe",
    "structure_confirmation_filter",
    "stress_option_position",
    "validate_market_clusters",
    "validate_backtest_result",
    "vwap_stretch_filter",
    "write_replication_report",
]
