#cspell:words ATR SUPER_TREND ADX RSI DEMA
ATR_PERIOD = 14
SUPER_TREND_PERIOD = 10
SUPER_TREND_MULTIPLIER = 3
ADX_PERIOD = 14
RSI_PERIOD = 14
DEMA_PERIOD = 20
STOP_LOSS_PERCENTAGE = 0.02
RR_RATIO = 2
ACCOUNT_SIZE = 10000
PERCENTAGE_INVESTED = 1.0
MARKET = "SPY"
PERIOD = "2y"
INTERVAL = "4h"